### ISSUE TITLE
Unable to install ppa:deadsnakes/ppa

### ISSUE THREAD

**Issue by abdullahIsa** [miroslavpejic85/mirotalksfu#154]
Hello i ran this command "add-apt-repository -y ppa:deadsnakes/ppa" in my Ubuntu Vm but i kept getting error, what to do thanks.

Error:
`Found existing deb entry in /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
Adding deb entry to /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
Found existing deb-src entry in /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
Adding key to /etc/apt/trusted.gpg.d/deadsnakes-ubuntu-ppa.gpg with fingerprint F23C5A6CF475977595C89F51BA6932366A755776
Hit:1 https://repository.monarx.com/repository/ubuntu-lunar lunar InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu lunar InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu lunar-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu lunar-backports InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu lunar-security InRelease
Ign:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu lunar InRelease
Err:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu lunar Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

Using:
Ubuntu 23.04
Python 3.11.4

**Comment by miroslavpejic85** [comment]
The error message you're seeing indicates that the repository for the `deadsnakes` PPA does not have a release file for Ubuntu 23.04 (Lunar Lobster). This is why the `apt` command is failing to add it.

The `deadsnakes` PPA may not support Ubuntu 23.04 yet, or the repository URL might not be set up correctly for this version. Here are a few steps you can take to resolve the issue:

1. **Check the `deadsnakes` PPA page**: Sometimes, the repository might not be available for the latest Ubuntu release immediately. Check the [deadsnakes PPA page](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) to see if there's an update or any information regarding support for Ubuntu 23.04.

2. **Use an older Ubuntu version's PPA**: If the `deadsnakes` PPA isn't available for Ubuntu 23.04, you can try using the PPA for an older version of Ubuntu that is supported by the `deadsnakes` PPA. For example, you can try using the repository for Ubuntu 22.04 (Jammy Jellyfish).

To do this, manually add the repository entry for `jammy`:

```bash
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo sed -i 's/lunar/jammy/g' /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
sudo apt update
```

This manually edits the sources list to point to the `jammy` repository instead of `lunar`.

3. **Check for alternative repositories**: Sometimes there are other PPAs or repositories that can be used to install the desired Python versions. For instance, Ubuntu's official repositories might already have the Python version you need.

4. **Build from source**: If the desired Python version is not available through any repository, you might consider building Python from source. This can be more time-consuming but ensures you can get the specific version you need.

Here’s how to build Python from source:

```bash
sudo apt update
sudo apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev curl libbz2-dev

# Download the source code for the desired Python version
curl -O https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz
tar -xf Python-3.11.4.tgz
cd Python-3.11.4

# Configure and install
./configure --enable-optimizations
make -j $(nproc)
sudo make altinstall
```

This will install Python 3.11.4 as `python3.11` without interfering with the system's default Python version.

By trying one of these solutions, you should be able to resolve the issue and install the desired Python version on your Ubuntu 23.04 system.

For further questions or need help use the discord forum instead. 

Thank you!
