### ISSUE TITLE
help to open in vs.net

### ISSUE THREAD

**Issue by dotnethii** [miroslavpejic85/mirotalksfu#16]
hi please help to open in visual studio 2019

**Comment by Jaideep25** [comment]
Hello @dotnethii ! This needs WSL (here also few may not work) based system to work, or Linux (and other such distros), or Mac to work, you will need to download some dependencies in WSL then like build-essential, python, node.js, etc! 
It won't run properly in VS 2019 (exceptions their), because their are still some bugs in GYP project and this uses mediasoup server, in turn mediasoup uses GYP deps, hope you understand and it helps! For more info check out mediasoup discourse community!
Thanks!
Regards.

**Comment by dotnethii** [comment]
OOOOOh noooo :( .Thanks.
