### ISSUE TITLE
No Audio from Participants in Screen Recording

### ISSUE THREAD

**Issue by hrauvc** [miroslavpejic85/mirotalksfu#164]
# Bug Report: No Audio from Participants in Screen Recording

## Description

When recording the screen during a meeting, the audio from other participants is not captured in the recording. This results in a video with only the presenter's audio, which is not ideal for reviewing discussions or sharing the recording with others.

## Expected Behavior

When recording the screen, the audio from all participants in the meeting should be captured in the recording, ensuring that the full discussion is preserved.

## Steps to Reproduce

1. Start a meeting as a host or participant.
2. Begin recording the screen using the built-in recording option.
3. Have a conversation with other participants during the meeting.
4. Stop the recording and review the video.

## Actual Behavior

The resulting recording only includes the audio from the person who initiated the recording, while the voices of other participants are missing.

**Comment by miroslavpejic85** [comment]
Hi hrauvc,

We have also tested the task in question and can confirm that it is functioning as expected. Participants' audio is recorded correctly, even during screen sharing.

![mirotalk-sfu-screen-recording](https://github.com/user-attachments/assets/49844f8a-31aa-4891-b2b4-3cdf21c88b77)

Please ensure you are using the **latest** version of MiroTalk SFU, which is **1.5.61**.

For further assistance, kindly use our community forum instead of opening an issue here. The GitHub is primarily for bug related to live demo issues, not for **derived projects**.

Thank you, and have a great weekend!

Best regards,  
Miroslav
