### ISSUE TITLE
I want my screen recording to start automatically by default, without needing to press any button or select any tab. The recording should start on its own, and when the meeting ends, the recording should stop automatically. The current screen I’m referring to is the calling screen on the **mirotalksfu** site.

### ISSUE THREAD

**Issue by haseebkhalid907** [miroslavpejic85/mirotalksfu#177]
### Feature request

I want my screen recording to start automatically by default, without needing to press any button or select any tab. The recording should start on its own, and when the meeting ends, the recording should stop automatically. The current screen I’m referring to is the calling screen on the **mirotalksfu** site.

### Pros

I want my screen recording to start automatically by default, without needing to press any button or select any tab. The recording should start on its own, and when the meeting ends, the recording should stop automatically. The current screen I’m referring to is the calling screen on the **mirotalksfu** site.

**Comment by miroslavpejic85** [comment]
To ensure `user privacy` and comply with `browser policies`, `automatic screen recording cannot start by default` without user interaction. Most modern browsers require explicit user consent when initiating screen sharing or recording due to privacy and security guidelines. Specifically, the [getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) API mandates user interaction to start screen sharing, which means the user needs to actively select the screen or tab they wish to share.
