### ISSUE TITLE
Users can not rejoin room

### ISSUE THREAD

**Issue by jhjacobs81** [miroslavpejic85/mirotalksfu#39]
After a user leaves a running meeting, he/she can not rejoin the running meeting again. they keep seeing a black box with a circle. there's no info someone likes to join so we can't allow them again.

**Comment by miroslavpejic85** [comment]
Hello @jhjacobs81, First of all good morning ;)
Do you have this problem on my Live Demo? Because I just tried and I don't see the problem mentioned. When a user leaves the room currently he is redirected to the survey page, which I recently implemented to gather some info in order to improve MiroTalk service. If you want to return to the room just click on the following icon

![survey](https://user-images.githubusercontent.com/70838434/152869975-79c7eb27-ad29-4a26-8026-aff06f845a71.png)

That redirect you on this page: https://sfu.mirotalk.org/newroom or you can go back to the landing page: https://sfu.mirotalk.org then type the name of the room where you want to rejoin :) ... 

Regards
