### ISSUE TITLE
Screen share not working fine

### ISSUE THREAD

**Issue by aseelhadid** [miroslavpejic85/mirotalksfu#75]
The screen sharing feature does not work properly when the feature is activated, only the first moment is shared and the user is often taken out of the session

**Comment by miroslavpejic85** [comment]
Hello @aseelhadid,

I'm sorry but I don't have enough elements to understand what you mean.

If you think it's a bug, please use the bug template by completing each required steps, such as the steps to reproduce it, devices involved, it's on my live demo or your own instance ? ... and so on. 

On default the screen sharing is enabled if the device support it, you not need to activate this feature.

I'm using the screen sharing often (for a very long time), and have not encountered any issues with disconnection or anything else, perhaps it's due to poor connectivity, low bandwidth, non MiroTalk related issues.

If you have pleasure, join with us on [Discord](https://discord.gg/rgGYfeYW3N) - `help & support channel` (also good for discussion like this)

Thank you
