### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by Raj-nexever** [miroslavpejic85/mirotalksfu#92]
### Screen goes blank

I installed your product it shows create and join room link but when I click on join it shows blank screen and there is no error on console as well

### To Reproduce

1. Go to http://ownurhealth.org:3010/
2. Click on 'Join room'

### Expected behavior
Video and audio call should work fine.

![image_2023_01_30T09_06_10_337Z](https://user-images.githubusercontent.com/104357477/215433640-9dca0341-9a1e-4545-b785-0b7f1df325bf.png)
Please complete the following information:

 - Browser [Chrome, Safari]

**Comment by miroslavpejic85** [comment]
Hello @Raj-nexever,

Use always the `latest` version of MiroTalk and browsers too.

You need to expose it on `https` instead of `http`

Please, follow also the documentation provided on how to self host it here:

https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md

Join with us on [Discord](https://discord.gg/rgGYfeYW3N) on channel `help & support` for questions like this and

check out also the closed relative issues like:

https://github.com/miroslavpejic85/mirotalksfu/issues/88

...

Thank you!
